#!/bin/bash

file_he='tmp/1-file_list-helpers.txt'
file_mo='tmp/1-file_list-models.txt'
file_co='tmp/1-file_list-controllers.txt'
file_vi='tmp/1-file_list-views.txt'
file_po='tmp/1-file_list-policies.txt'
file_jo='tmp/1-file_list-jobs.txt'
file_pr='tmp/1-file_list-presenters.txt'
file_se='tmp/1-file_list-services.txt'

sh pg-start.sh

echo '------------------------------------'
echo 'Listing the helper files in the file'
echo $file_he
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_he
echo '-------------------' >> $file_he
echo 'HELPERS' >> $file_he
tree spec/helpers >> $file_he
echo '' >> $file_he
tree app/helpers >> $file_he
echo '' >> $file_he

echo '-----------------------------------'
echo 'Listing the model files in the file'
echo $file_mo
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_mo
echo '------' >> $file_mo
echo 'MODELS' >> $file_mo
tree spec/models >> $file_mo
echo '' >> $file_mo
tree app/models >> $file_mo

echo '----------------------------------------'
echo 'Listing the controller files in the file'
echo $file_co
echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_co
echo '-----------' >> $file_co
echo 'CONTROLLERS' >> $file_co
tree spec/controllers >> $file_co
echo '' >> $file_co
tree app/controllers >> $file_co

echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_vi
echo '---------------------------' >> $file_vi
echo 'VIEWS AND INTEGRATION TESTS' >> $file_vi
echo '' >> $file_vi
echo '----------------' >> $file_vi
echo 'config/routes.rb' >> $file_vi
cat config/routes.rb >> $file_vi
echo '----------------' >> $file_vi
tree spec/features >> $file_vi
echo '' >> $file_vi
tree app/views >> $file_vi

echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_po
echo '--------' >> $file_po
echo 'POLICIES' >> $file_po
echo '' >> $file_po
echo '-----------' >> $file_po
tree spec/policies >> $file_po
echo '' >> $file_po
tree app/policies >> $file_po

echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_jo
echo '----' >> $file_jo
echo 'JOBS' >> $file_jo
echo '' >> $file_jo
echo '-------' >> $file_jo
tree spec/jobs >> $file_jo
echo '' >> $file_jo
tree app/jobs >> $file_jo

echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_pr
echo '----------' >> $file_pr
echo 'PRESENTERS' >> $file_pr
echo '' >> $file_pr
echo '-------------' >> $file_pr
tree spec/presenters >> $file_pr
echo '' >> $file_pr
tree app/presenters >> $file_pr

echo 'This file was AUTOMATICALLY generated by the outline-short.sh script.' > $file_se
echo '--------' >> $file_se
echo 'SERVICES' >> $file_se
echo '' >> $file_se
echo '------------' >> $file_se
tree spec/services >> $file_se
echo '' >> $file_se
tree app/services >> $file_se

echo 'FINISHED compiling the list of files that make up the MVC structure'
echo '-------------------------------------------------------------------'

echo '******************************'
echo 'outline-short.sh OUTPUT FILES:'
echo $file_he
echo $file_mo
echo $file_co
echo $file_vi
echo $file_po
echo $file_jo
echo $file_pr
echo $file_se
echo
